theme: jekyll-theme-minimal
title: Nicolas Jao
description: |
  I'm a speculative fiction author whose stories often include elements of Chinese or Filipino culture. I am studying for a BTech in Automation Engineering from McMaster University and I live in the Toronto suburbs.
  
  This is a collection of all my finished works. You can read them here. Keep checking this site to stay updated for more works!
